[alembic]
script_location = apps/api/migrations
prepend_sys_path = .
path_separator = os
timezone = UTC

[loggers]
keys = root

[handlers]
keys = null

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = null
qualname =

[handler_null]
class = logging.NullHandler
args = ()
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)s %(name)s %(message)s
